In [4]:
%pip uninstall scikit-learm -y
%pip install scikit-learn

Found existing installation: scikit-learm 0.2
Uninstalling scikit-learm-0.2:
  Successfully uninstalled scikit-learm-0.2
Note: you may need to restart the kernel to use updated packages.
Collecting scikit-learn
  Using cached scikit_learn-1.9.1-cp314-cp314-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (9.3 kB)
Requirement already satisfied: numpy>=1.24.1 in /home/harsha/Desktop/AI & ML/myenv/lib/python3.14/site-packages (from scikit-learn) (2.5.4)
Collecting scipy>=1.10.0 (from scikit-learn)
  Using cached scipy-1.18.1-cp314-cp314-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (62 kB)
Collecting joblib>=1.4.0 (from scikit-learn)
  Using cached joblib-1.6.0-py3-none-any.whl.metadata (6.5 kB)
Collecting narwhals>=2.0.1 (from scikit-learn)
  Using cached narwhals-2.27.1-py3-none-any.whl.metadata (15 kB)
Collecting threadpoolctl>=3.5.0 (from scikit-learn)
  Using cached threadpoolctl-3.7.0-py3-none-any.whl.metadata (24 kB)
Collecting cloudpickle>=3.0 (from joblib>=1.4.0->scikit-learn)
  Using cached cloudpickle-3.1.2-py3-none-any.whl.metadata (7.1 kB)
Using cached scikit_learn-1.9.1-cp314-cp314-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (9.2 MB)
Using cached joblib-1.6.0-py3-none-any.whl (306 kB)
Using cached cloudpickle-3.1.2-py3-none-any.whl (22 kB)
Using cached narwhals-2.27.1-py3-none-any.whl (483 kB)
Using cached scipy-1.18.1-cp314-cp314-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (35.3 MB)
Using cached threadpoolctl-3.7.0-py3-none-any.whl (26 kB)
Installing collected packages: threadpoolctl, scipy, narwhals, cloudpickle, joblib, scikit-learn
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6/6 [scikit-learn]0m 5/6 [scikit-learn]]
Successfully installed cloudpickle-3.1.2 joblib-1.6.0 narwhals-2.27.1 scikit-learn-1.9.1 scipy-1.18.1 threadpoolctl-3.7.0
Note: you may need to restart the kernel to use updated packages.

In [5]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import sklearn
from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline, make_pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import HuberRegressor
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

In [6]:
df=pd.read_csv(r'/home/harsha/Desktop/AI & ML/student_makes_pred/StudentPerformanceFactors.csv')

In [7]:
df.head()

,Hours_Studied,Attendance,Parental_Involvement,Access_to_Resources,Extracurricular_Activities,Sleep_Hours,Previous_Scores,Motivation_Level,Internet_Access,Tutoring_Sessions,Family_Income,Teacher_Quality,School_Type,Peer_Influence,Physical_Activity,Learning_Disabilities,Parental_Education_Level,Distance_from_Home,Gender,Exam_Score
0,23,84,Low,High,No,7,73,Low,Yes,0,Low,Medium,Public,Positive,3,No,High School,Near,Male,67
1,19,64,Low,Medium,No,8,59,Low,Yes,2,Medium,Medium,Public,Negative,4,No,College,Moderate,Female,61
2,24,98,Medium,Medium,Yes,7,91,Medium,Yes,2,Medium,Medium,Public,Neutral,4,No,Postgraduate,Near,Male,74
3,29,89,Low,Medium,Yes,8,98,Medium,Yes,1,Medium,Medium,Public,Negative,4,No,High School,Moderate,Male,71
4,19,92,Medium,Medium,Yes,6,65,Medium,Yes,3,Medium,High,Public,Neutral,4,No,College,Near,Female,70

In [8]:
df.tail()

,Hours_Studied,Attendance,Parental_Involvement,Access_to_Resources,Extracurricular_Activities,Sleep_Hours,Previous_Scores,Motivation_Level,Internet_Access,Tutoring_Sessions,Family_Income,Teacher_Quality,School_Type,Peer_Influence,Physical_Activity,Learning_Disabilities,Parental_Education_Level,Distance_from_Home,Gender,Exam_Score
6602,25,69,High,Medium,No,7,76,Medium,Yes,1,High,Medium,Public,Positive,2,No,High School,Near,Female,68
6603,23,76,High,Medium,No,8,81,Medium,Yes,3,Low,High,Public,Positive,2,No,High School,Near,Female,69
6604,20,90,Medium,Low,Yes,6,65,Low,Yes,3,Low,Medium,Public,Negative,2,No,Postgraduate,Near,Female,68
6605,10,86,High,High,Yes,6,91,High,Yes,2,Low,Medium,Private,Positive,3,No,High School,Far,Female,68
6606,15,67,Medium,Low,Yes,9,94,Medium,Yes,0,Medium,Medium,Public,Positive,4,No,Postgraduate,Near,Male,64

In [10]:
print('Data Shape:',df.shape)
print('\n Column Names:')
print(df.columns)
print('\n Data information:')
print(df.info)
print('\n Misssing Values:')
print(df.isnull().sum())
print('\n nStatistical Summary:')
print(df.describe())

Data Shape: (6607, 20)

 Column Names:
Index(['Hours_Studied', 'Attendance', 'Parental_Involvement',
       'Access_to_Resources', 'Extracurricular_Activities', 'Sleep_Hours',
       'Previous_Scores', 'Motivation_Level', 'Internet_Access',
       'Tutoring_Sessions', 'Family_Income', 'Teacher_Quality', 'School_Type',
       'Peer_Influence', 'Physical_Activity', 'Learning_Disabilities',
       'Parental_Education_Level', 'Distance_from_Home', 'Gender',
       'Exam_Score'],
      dtype='str')

 Data information:
<bound method DataFrame.info of       Hours_Studied  Attendance Parental_Involvement Access_to_Resources  \
0                23          84                  Low                High
1                19          64                  Low              Medium
2                24          98               Medium              Medium
3                29          89                  Low              Medium
4                19          92               Medium              Medium
...             ...         ...                  ...                 ...
6602             25          69                 High              Medium
6603             23          76                 High              Medium
6604             20          90               Medium                 Low
6605             10          86                 High                High
6606             15          67               Medium                 Low

     Extracurricular_Activities  Sleep_Hours  Previous_Scores  \
0                            No            7               73
1                            No            8               59
2                           Yes            7               91
3                           Yes            8               98
4                           Yes            6               65
...                         ...          ...              ...
6602                         No            7               76
6603                         No            8               81
6604                        Yes            6               65
6605                        Yes            6               91
6606                        Yes            9               94

     Motivation_Level Internet_Access  Tutoring_Sessions Family_Income  \
0                 Low             Yes                  0           Low
1                 Low             Yes                  2        Medium
2              Medium             Yes                  2        Medium
3              Medium             Yes                  1        Medium
4              Medium             Yes                  3        Medium
...               ...             ...                ...           ...
6602           Medium             Yes                  1          High
6603           Medium             Yes                  3           Low
6604              Low             Yes                  3           Low
6605             High             Yes                  2           Low
6606           Medium             Yes                  0        Medium

     Teacher_Quality School_Type Peer_Influence  Physical_Activity  \
0             Medium      Public       Positive                  3
1             Medium      Public       Negative                  4
2             Medium      Public        Neutral                  4
3             Medium      Public       Negative                  4
4               High      Public        Neutral                  4
...              ...         ...            ...                ...
6602          Medium      Public       Positive                  2
6603            High      Public       Positive                  2
6604          Medium      Public       Negative                  2
6605          Medium     Private       Positive                  3
6606          Medium      Public       Positive                  4

     Learning_Disabilities Parental_Education_Level Distance_from_Home  \
0                       No              High School               Near
1                       No                  College           Moderate
2                       No             Postgraduate               Near
3                       No              High School           Moderate
4                       No                  College               Near
...                    ...                      ...                ...
6602                    No              High School               Near
6603                    No              High School               Near
6604                    No             Postgraduate               Near
6605                    No              High School                Far
6606                    No             Postgraduate               Near

      Gender  Exam_Score
0       Male          67
1     Female          61
2       Male          74
3       Male          71
4     Female          70
...      ...         ...
6602  Female          68
6603  Female          69
6604  Female          68
6605  Female          68
6606    Male          64

[6607 rows x 20 columns]>

 Misssing Values:
Hours_Studied                  0
Attendance                     0
Parental_Involvement           0
Access_to_Resources            0
Extracurricular_Activities     0
Sleep_Hours                    0
Previous_Scores                0
Motivation_Level               0
Internet_Access                0
Tutoring_Sessions              0
Family_Income                  0
Teacher_Quality               78
School_Type                    0
Peer_Influence                 0
Physical_Activity              0
Learning_Disabilities          0
Parental_Education_Level      90
Distance_from_Home            67
Gender                         0
Exam_Score                     0
dtype: int64

 nStatistical Summary:
       Hours_Studied   Attendance  Sleep_Hours  Previous_Scores  \
count    6607.000000  6607.000000   6607.00000      6607.000000
mean       19.975329    79.977448      7.02906        75.070531
std         5.990594    11.547475      1.46812        14.399784
min         1.000000    60.000000      4.00000        50.000000
25%        16.000000    70.000000      6.00000        63.000000
50%        20.000000    80.000000      7.00000        75.000000
75%        24.000000    90.000000      8.00000        88.000000
max        44.000000   100.000000     10.00000       100.000000

       Tutoring_Sessions  Physical_Activity   Exam_Score
count        6607.000000        6607.000000  6607.000000
mean            1.493719           2.967610    67.235659
std             1.230570           1.031231     3.890456
min             0.000000           0.000000    55.000000
25%             1.000000           2.000000    65.000000
50%             1.000000           3.000000    67.000000
75%             2.000000           4.000000    69.000000
max             8.000000           6.000000   101.000000

In [ ]:
FEATURES = [
    'Hours_Studied', 'Attendance', 'Previous_Scores',
    'Sleep_Hours', 'Tutoring_Sessions', 'Physical_Activity',
]
X = df[FEATURES]
y = df['Exam_Score']

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [ ]:
print(X_train.shape)
print(X_test.shape)

In [ ]:
model = Pipeline([
    ('preprocessor', make_pipeline(SimpleImputer(strategy='median'), StandardScaler())),
    ('regressor', HuberRegressor(epsilon=2.0, alpha=0.0001, max_iter=500)),
])
model.fit(X_train, y_train)

print("Model training completed!")

In [ ]:
y_pred = model.predict(X_test)

print("Actual scores:")
print(y_test.head())

print("\nPredicted scores:")
print(y_pred[:5])

In [ ]:
mae = mean_absolute_error(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)
rmse = np.sqrt(mse)
r2 = r2_score(y_test, y_pred)

print("MAE:", mae)
print("MSE:", mse)
print("RMSE:", rmse)
print("R² Score:", r2)

In [ ]:
plt.figure(figsize=(8, 5))

plt.scatter(y_test, y_pred)

plt.xlabel("Actual Exam Scores")
plt.ylabel("Predicted Exam Scores")
plt.title("Actual vs Predicted Student Scores")

plt.show()

In [ ]:
import joblib

joblib.dump(model, "student_performance_model.pkl")